url: https://y7kim.github.io
baseurl: ""

# Site settings
title: Derk Slagman
email: derk.slagman@gmail.com
description: Salesforce | .NET | Software Engineer

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/Derk87
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/dslagman
  - title: linkedin
    url: https://www.linkedin.com/in/derkslagman/
  - title: github
    url: https://github.com/dslagman

# Postal address (add as many lines as necessary)
address:
  - line:
  - line:

# Build settings
markdown: kramdown
permalink: pretty

collections:
  - history